name: Docker Publish

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USER: cis120
  IMAGE_NAME: cis120-docker

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ['amd64'] # arm64
        dockerfiles: ['alpine', 'ubuntu', 'alpine-java', 'alpine-ocaml']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.CIS120_DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          export TAG=${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ matrix.dockerfiles }}-${{ matrix.arch }}
          docker buildx build --platform ${{ matrix.arch }} --file ${{ matrix.dockerfiles }}.dockerfile --tag $TAG .
          docker image push $TAG
