name: Docker Publish

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USER: cis120
  IMAGE_NAME: cis120-docker

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ['amd64', 'arm64']
        dockerfiles: ['alpine', 'ubuntu', 'alpine-java', 'alpine-ocaml']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}

      - name: Build image
        run: |
          docker buildx --platform ${{ matrix.arch }} --file ${{ matrix.dockerfiles }}.dockerfile --tag $DOCKERHUB_USER/$IMAGE_NAME:${{ GITHUB_SHA }} .
          docker tag $DOCKERHUB_USER/$IMAGE_NAME:${{ GITHUB_SHA }} $DOCKERHUB_USER/${{ matrix.dockerfiles }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CIS120_DOCKERHUB_USERNAME }}
          password: ${{ secrets.CIS120_DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker image push --all-tags $DOCKERHUB_USER/$IMAGE_NAME
